export const EVENTS = {
  ROOM: {
    CREATE_PRIVATE: 'ROOM_CREATE_PRIVATE',
    CREATE_GROUP: 'ROOM_CREATE_GROUP',
    CREATED: 'ROOM_CREATED',
    JOIN: 'JOIN_ROOM',
    UPDATE: 'ROOM_UPDATE',
    LEAVE: 'ROOM_LEAVE',
    UPDATED: 'ROOM_UPDATED'
  },

  MESSAGE: {
    TYPING: 'MESSAGE_TYPING',
    MESSAGE_CREATE: 'MESSAGE_CREATE',
    NEW_MESSAGE_CREATED: 'MESSAGE_CREATED',
    RESPONSE_TYPING: 'MESSAGE_SUBMIT_TYPING',
    READ: 'MESSAGE_READ',
    READED: 'MESSAGE_WAS_READ',
  },

  USER: {
    ENTER: 'USER_ENTER',
    LEAVE: 'USER_LEAVE'
  }
} as const;